### ISSUE TITLE
ClientUser.SetPresence doesnt work

### ISSUE THREAD

**Issue by EndermanHackerVN** [TheDevYellowy/dsb.js#3]
My snippet:

```js
client.user.setPresence({
        status: 'idle',
        activities: [
            {
                name: 'nightfall',
                type: 'WATCHING'
            }
        ]
    })
```

![image](https://user-images.githubusercontent.com/67498765/157903860-78b477d1-cdf5-4c56-bb1e-0fbf06c169c4.png)

**Comment by TheDevYellowy** [comment]
I think it may be a bot only thing but I'll look into it

**Comment by EndermanHackerVN** [comment]
@TheDevYellowy I used to do ClientUser.setPresence() on djs 12.5.3 with the tokenType trick and it still works fine, I guess its an API update. Anyways, thanks for the fast reply!

**Comment by TheDevYellowy** [comment]
No problem and yeah, discord does love to update their api to fuck us over
